---
name: Ingress proxy
version: 0.2.1
slug: ingress_proxy
description: nginx reverse proxy to expose network resources through HA ingress
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
init: false
ingress: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
options:
  destination: "http://atlantic.oceanic.io"
schema:
  destination: str?